# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_STM32) += \
	stm32mp135f-dk.dtb \
	stm32mp135f-dk-a7-examples.dtb \
	myb-stm32mp135x-512m.dtb \
	myb-stm32mp135x-512m-hdmi.dtb \
	myb-stm32mp135x-256m.dtb \
	myb-stm32mp135x-256m-hdmi.dtb

